/**
 * @fileoverview Employee Management Type Definitions
 *
 * This module defines all TypeScript interfaces and types for the employee management system.
 * Includes types for employees, roles, permissions, and their relationships.
 *
 * Key Features:
 * - Employee CRUD operations with role-based access control
 * - Role and permission management for RBAC system
 * - Pagination and filtering for employee lists
 * - Data transfer objects (DTOs) for API requests
 *
 * @module types/employee
 * @created 2026-02-14
 * @updated 2026-02-14
 */

/**
 * @interface Employee
 * @description Complete employee record from the database
 *
 * Represents a full employee record with all fields from the employees table.
 * Includes auto-generated employee_number (EMP-XXXXXX format) and optional
 * role information joined from the roles table.
 *
 * @property {number} id - Primary key, auto-incrementing integer
 * @property {string} employee_number - Unique employee identifier (EMP-000001, EMP-000002, etc.)
 * @property {string | null} user_id - Optional UUID linking to users table for system login
 * @property {string} first_name - Employee first name (max 100 characters, required)
 * @property {string} last_name - Employee last name (max 100 characters, required)
 * @property {string} email - Unique email address (max 255 characters, required)
 * @property {string | null} phone - Optional phone number (max 20 characters)
 * @property {string} hire_date - Date employee was hired, ISO format YYYY-MM-DD
 * @property {string | null} termination_date - Date employee was terminated, ISO format YYYY-MM-DD (null if active)
 * @property {number} role_id - Foreign key to roles table (required)
 * @property {string} [role_name] - Role name joined from roles table (optional, only in list/detail queries)
 * @property {string | null} assigned_terminal_id - UUID of assigned POS terminal (null if no terminal assigned)
 * @property {boolean} is_active - Employee active status (true = active, false = deactivated/terminated)
 * @property {string} created_at - Timestamp when record was created, ISO 8601 format
 * @property {string} updated_at - Timestamp when record was last updated, ISO 8601 format
 *
 * @example
 * const employee: Employee = {
 *   id: 1,
 *   employee_number: "EMP-000001",
 *   user_id: "550e8400-e29b-41d4-a716-446655440000",
 *   first_name: "John",
 *   last_name: "Doe",
 *   email: "john.doe@company.com",
 *   phone: "555-0100",
 *   hire_date: "2026-02-14",
 *   termination_date: null,
 *   role_id: 2,
 *   role_name: "cashier",
 *   assigned_terminal_id: "660e8400-e29b-41d4-a716-446655440001",
 *   is_active: true,
 *   created_at: "2026-02-14T10:00:00.000Z",
 *   updated_at: "2026-02-14T10:00:00.000Z"
 * };
 */
export interface Employee {
  id: number;
  employee_number: string;
  user_id: string | null;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  hire_date: string;
  termination_date: string | null;
  role_id: number;
  role_name?: string;
  assigned_terminal_id: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * @interface CreateEmployeeDTO
 * @description Data transfer object for creating a new employee
 *
 * Used in POST /api/v1/employees endpoint. All required fields must be provided.
 * The employee_number is auto-generated by database trigger and should NOT be included.
 *
 * @property {string} first_name - Employee first name (required, max 100 characters)
 * @property {string} last_name - Employee last name (required, max 100 characters)
 * @property {string} email - Unique email address (required, max 255 characters, must be valid email format)
 * @property {string} [phone] - Optional phone number (max 20 characters)
 * @property {string} hire_date - Date of hire in ISO format YYYY-MM-DD (required, cannot be changed after creation)
 * @property {number} role_id - Foreign key to roles table (required, must be valid role ID)
 * @property {string} [assigned_terminal_id] - Optional UUID of POS terminal to assign (must be valid UUID)
 * @property {string} [user_id] - Optional UUID linking to users table for system login (must be valid UUID)
 *
 * @example
 * const newEmployee: CreateEmployeeDTO = {
 *   first_name: "Jane",
 *   last_name: "Smith",
 *   email: "jane.smith@company.com",
 *   phone: "555-0200",
 *   hire_date: "2026-02-14",
 *   role_id: 2,
 *   assigned_terminal_id: "770e8400-e29b-41d4-a716-446655440002"
 * };
 */
export interface CreateEmployeeDTO {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  hire_date: string;
  role_id: number;
  assigned_terminal_id?: string | null;
  user_id?: string | null;
}

/**
 * @interface UpdateEmployeeDTO
 * @description Data transfer object for updating an existing employee
 *
 * Used in PUT /api/v1/employees/:id endpoint. All fields are optional - only
 * include fields you want to update. Note: hire_date and employee_number
 * cannot be updated after creation.
 *
 * @property {string} [first_name] - Updated first name (max 100 characters)
 * @property {string} [last_name] - Updated last name (max 100 characters)
 * @property {string} [email] - Updated email (max 255 characters, must remain unique)
 * @property {string | null} [phone] - Updated phone number (max 20 characters, null to clear)
 * @property {number} [role_id] - Updated role ID (must be valid role ID)
 * @property {string | null} [assigned_terminal_id] - Updated terminal assignment (UUID, null to clear)
 * @property {string | null} [termination_date] - Set termination date in ISO format YYYY-MM-DD (used when terminating employee)
 * @property {boolean} [is_active] - Set active status (false to deactivate employee)
 *
 * @example
 * const updates: UpdateEmployeeDTO = {
 *   phone: "555-0299",
 *   role_id: 3,
 *   assigned_terminal_id: "880e8400-e29b-41d4-a716-446655440003"
 * };
 */
export interface UpdateEmployeeDTO {
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string | null;
  role_id?: number;
  assigned_terminal_id?: string | null;
  termination_date?: string | null;
  is_active?: boolean;
}

/**
 * @interface EmployeeFilters
 * @description Filter options for employee list queries
 *
 * Used in GET /api/v1/employees endpoint to filter the employee list.
 * All filters are optional and can be combined.
 *
 * @property {number} [role_id] - Filter by specific role ID (only show employees with this role)
 * @property {boolean} [is_active] - Filter by active status (true = active only, false = inactive only, undefined = all)
 * @property {string} [search] - Search text to match against name, email, or employee_number (case-insensitive partial match)
 *
 * @example
 * const filters: EmployeeFilters = {
 *   role_id: 2,
 *   is_active: true,
 *   search: "john"
 * };
 */
export interface EmployeeFilters {
  role_id?: number;
  is_active?: boolean;
  search?: string;
}

/**
 * @interface EmployeePagination
 * @description Pagination options for employee list queries
 *
 * Used in GET /api/v1/employees endpoint to paginate results.
 * Both fields are optional with defaults applied by the backend.
 *
 * @property {number} [page] - Page number to retrieve (default: 1, min: 1)
 * @property {number} [limit] - Number of employees per page (default: 10, min: 1, max: 100)
 *
 * @example
 * const pagination: EmployeePagination = {
 *   page: 2,
 *   limit: 20
 * };
 */
export interface EmployeePagination {
  page?: number;
  limit?: number;
}

/**
 * @interface EmployeeListResult
 * @description Response format for paginated employee list queries
 *
 * Returned by GET /api/v1/employees endpoint. Contains the employee array
 * plus pagination metadata for building UI pagination controls.
 *
 * @property {Employee[]} employees - Array of employee records for the current page
 * @property {number} total - Total number of employees matching the filters (across all pages)
 * @property {number} page - Current page number (1-indexed)
 * @property {number} limit - Number of employees per page
 * @property {number} totalPages - Total number of pages available (calculated from total/limit)
 *
 * @example
 * const result: EmployeeListResult = {
 *   employees: [
 *     { id: 1, employee_number: "EMP-000001", first_name: "John", ... },
 *     { id: 2, employee_number: "EMP-000002", first_name: "Jane", ... }
 *   ],
 *   total: 25,
 *   page: 1,
 *   limit: 10,
 *   totalPages: 3
 * };
 */
export interface EmployeeListResult {
  employees: Employee[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * @interface Role
 * @description Role record for role-based access control (RBAC)
 *
 * Represents a role in the RBAC system. Roles define job functions (admin, manager, cashier)
 * and have associated permissions that control what users in that role can do.
 *
 * @property {number} id - Primary key, auto-incrementing integer
 * @property {string} role_name - Unique role identifier (lowercase, e.g., "admin", "cashier", max 50 characters)
 * @property {string | null} description - Human-readable role description (max 255 characters, optional)
 * @property {boolean} is_active - Role active status (inactive roles cannot be assigned to new employees)
 * @property {string} created_at - Timestamp when role was created, ISO 8601 format
 * @property {string} updated_at - Timestamp when role was last updated, ISO 8601 format
 *
 * @example
 * const role: Role = {
 *   id: 2,
 *   role_name: "cashier",
 *   description: "Basic POS operations and customer management",
 *   is_active: true,
 *   created_at: "2026-02-14T08:00:00.000Z",
 *   updated_at: "2026-02-14T08:00:00.000Z"
 * };
 */
export interface Role {
  id: number;
  role_name: string;
  description: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * @interface CreateRoleDTO
 * @description Data transfer object for creating a new role
 *
 * Used in POST /api/v1/roles endpoint. After creating a role, use the
 * permission assignment endpoints to add permissions to it.
 *
 * @property {string} role_name - Unique role identifier (required, lowercase, max 50 characters, e.g., "supervisor")
 * @property {string} [description] - Optional human-readable description (max 255 characters)
 *
 * @example
 * const newRole: CreateRoleDTO = {
 *   role_name: "supervisor",
 *   description: "Supervise cashiers and handle voids/refunds"
 * };
 */
export interface CreateRoleDTO {
  role_name: string;
  description?: string | null;
}

/**
 * @interface UpdateRoleDTO
 * @description Data transfer object for updating an existing role
 *
 * Used in PUT /api/v1/roles/:id endpoint. All fields are optional.
 * Note: Changing role_name does not affect existing employee assignments.
 *
 * @property {string} [role_name] - Updated role identifier (must remain unique, max 50 characters)
 * @property {string | null} [description] - Updated description (max 255 characters, null to clear)
 * @property {boolean} [is_active] - Set active status (false to deactivate role, prevents new assignments)
 *
 * @example
 * const updates: UpdateRoleDTO = {
 *   description: "Updated role description",
 *   is_active: false
 * };
 */
export interface UpdateRoleDTO {
  role_name?: string;
  description?: string | null;
  is_active?: boolean;
}

/**
 * @interface Permission
 * @description Permission record for fine-grained access control
 *
 * Represents a single permission in the RBAC system. Permissions follow a
 * resource+action pattern (e.g., "transaction:create", "product:delete").
 * 35 total permissions cover all system resources.
 *
 * @property {number} id - Primary key, auto-incrementing integer
 * @property {string} permission_name - Unique permission identifier (e.g., "create_transaction", max 100 characters)
 * @property {string} resource - Resource type this permission applies to (e.g., "transaction", "product", max 50 characters)
 * @property {string} action - Action type (e.g., "create", "read", "update", "delete", max 20 characters)
 * @property {string | null} description - Human-readable description of what this permission allows (max 255 characters)
 * @property {string} created_at - Timestamp when permission was created, ISO 8601 format
 *
 * @example
 * const permission: Permission = {
 *   id: 5,
 *   permission_name: "void_transaction",
 *   resource: "transaction",
 *   action: "delete",
 *   description: "Void existing transaction",
 *   created_at: "2026-02-14T08:00:00.000Z"
 * };
 */
export interface Permission {
  id: number;
  permission_name: string;
  resource: string;
  action: string;
  description: string | null;
  created_at: string;
}

/**
 * @interface RoleWithPermissions
 * @description Extended role record including all assigned permissions
 *
 * Used in GET /api/v1/roles/:id endpoint to return a role with its complete
 * permission list. Extends the base Role interface.
 *
 * @extends Role
 * @property {Permission[]} permissions - Array of all permissions assigned to this role (empty array if no permissions)
 *
 * @example
 * const roleWithPerms: RoleWithPermissions = {
 *   id: 2,
 *   role_name: "cashier",
 *   description: "Basic POS operations",
 *   is_active: true,
 *   created_at: "2026-02-14T08:00:00.000Z",
 *   updated_at: "2026-02-14T08:00:00.000Z",
 *   permissions: [
 *     { id: 1, permission_name: "create_transaction", resource: "transaction", action: "create", ... },
 *     { id: 2, permission_name: "view_transaction", resource: "transaction", action: "read", ... }
 *   ]
 * };
 */
export interface RoleWithPermissions extends Role {
  permissions: Permission[];
}

/**
 * @interface AssignPermissionDTO
 * @description Data transfer object for assigning a permission to a role
 *
 * Used in POST /api/v1/roles/:roleId/permissions endpoint. Creates a many-to-many
 * relationship between a role and a permission in the role_permissions table.
 *
 * @property {number} role_id - Foreign key to roles table (required, must be valid role ID)
 * @property {number} permission_id - Foreign key to permissions table (required, must be valid permission ID)
 *
 * @example
 * const assignment: AssignPermissionDTO = {
 *   role_id: 2,
 *   permission_id: 5
 * };
 */
export interface AssignPermissionDTO {
  role_id: number;
  permission_id: number;
}
